executables:
  - name: "MonsterHunterRise.exe"
    signatures:
      - name: "STAGE_ADDRESS"
        signature: "E8 ?? ?? ?? ?? 48 8B 15 ?? ?? ?? ?? 48 89 54 24 ?? 48 85 D2"
        instruction_offset: 8
        is_relative: true

      - name: "MONSTER_ADDRESS"
        signature: "40 53 48 83 EC 20 48 8B 15 ?? ?? ?? ?? 48 8B D9 E8 ?? ?? ?? ?? 48 8B 15 ?? ?? ?? ?? 48 85 D2 74 08 48 8B CB E8 ?? ?? ?? ?? 48 8B 15 ?? ?? ?? ??"
        instruction_offset: 9
        is_relative: true

      - name: "LOCKON_ADDRESS"
        signature: "48 8B 05 ?? ?? ?? ?? 48 89 ?? 24 ?? ?? ?? 4C 8B ?? ?? 49 8B"
        instruction_offset: 3
        is_relative: true

      - name: "CHARACTER_ADDRESS"
        signature: "40 56 41 56 48 83 EC 38 4C 8B 35 ?? ?? ?? ?? 4C"
        instruction_offset: 11
        is_relative: true

      - name: "SAVE_ADDRESS"
        signature: "48 83 EC ?? 48 8B 05 ?? ?? ?? ?? 48 8B 50 ?? F2 0F 10 52 ?? 48 8B 15 ?? ?? ?? ??"
        instruction_offset: 23
        is_relative: true

      - name: "WEAPON_ADDRESS"
        signature: "48 8B 0D ?? ?? ?? ?? 8B 87 ?? ?? ?? ??"
        instruction_offset: 3
        is_relative: true

      - name: "ABNORMALITIES_ADDRESS"
        signature: "48 8B 15 ?? ?? ?? ?? 48 85 D2 74 08 48 8B CB E8 ?? ?? ?? ?? 48 8B 15 ?? ?? ?? ?? 48 85 D2 74 08 48 8B CB E8 ?? ?? ?? ?? 48 8B 15 ?? ?? ?? ?? 48 85 D2 74 0D"
        instruction_offset: 3
        is_relative: true

      - name: "ARGOSY_ADDRESS"
        signature: "48 8B 05 ?? ?? ?? ?? 48 8B CE 4C 89 AC 24 ?? 00 00 00"
        instruction_offset: 3
        is_relative: true

      - name: "TRAINING_DOJO_ADDRESS"
        signature: "40 55 48 83 EC ?? 48 8B 05 ?? ?? ?? ?? 48 8B E9 48 85 C0 74 ??"
        instruction_offset: 9
        is_relative: true

      - name: "CHAT_ADDRESS"
        signature: "48 8B 05 ?? ?? ?? ?? 48 8D 4C 24 ?? 48 8B D7 4C 8B 40 ?? E8 ?? ?? ?? ?? 0F 10 00"
        instruction_offset: 3
        is_relative: true

      - name: "CHAT_UI_ADDRESS"
        signature: "48 8B 05 ?? ?? ?? ?? 83 B8 ?? ?? ?? ?? 00 74 27"
        instruction_offset: 3
        is_relative: true

      - name: "SESSION_PLAYERS_ADDRESS"
        signature: "48 8B ?? ?? ?? ?? ?? 45 33 C0 48 8B ?? ?? ?? ?? ?? 48 8B 57 ?? 0F B6 68 10 E8 ?? ?? ?? ?? 3B E8"
        instruction_offset: 3
        is_relative: true

      - name: "UI_ADDRESS"
        signature: "48 8B 05 ?? ?? ?? ?? 83 B8 ?? ?? ?? ?? 00 74 27"
        instruction_offset: 3
        is_relative: true

      - name: "MOUSE_ADDRESS"
        signature: "48 8B 05 ?? ?? ?? ?? 4C 8B 5B ?? 0F 29 44 24"
        instruction_offset: 3
        is_relative: true

      - name: "QUEST_ADDRESS"
        signature: "48 8B 05 ?? ?? ?? ?? 83 B8 ?? ?? ?? ?? 02 75 ?? 83 B8 ?? ?? ?? ?? 07"
        instruction_offset: 3
        is_relative: true

      - name: "MEOWMASTERS_ADDRESS"
        signature: "C7 82 ?? ?? ?? ?? ?? ?? ?? ?? 48 8B 3D ?? ?? ?? ?? 85 C0 79"
        instruction_offset: 13
        is_relative: true

      - name: "COHOOT_ADDRESS"
        signature: "48 8B 05 ?? ?? ?? ?? 33 ED 48 8B 48 ?? 8B 41"
        instruction_offset: 3
        is_relative: true

      - name: "EVENTCAMERA_ADDRESS"
        signature: "48 8B 05 ?? ?? ?? ?? 38 98 ?? 00 00 00 0F 85 ?? ?? ?? ??"
        instruction_offset: 3
        is_relative: true

      - name: "GEAR_ADDRESS"
        signature: "48 8B 15 ?? ?? ?? ?? E9 ?? ?? ?? ?? 48 8B 15 ?? ?? ?? ?? 41 B8"
        instruction_offset: 3
        is_relative: true

      - name: "PLAYER_GEAR_ADDRESS"
        signature: "48 8B 05 ?? ?? ?? ?? 66 0F 6E 71 ?? 0F 5B F6"
        instruction_offset: 3
        is_relative: true

      - name: "SHARPNESS_ADDRESS"
        signature: "48 8B 15 ?? ?? ?? ?? 48 85 D2 74 08 48 8B CB E8 ?? ?? ?? ?? 48 8B 15 ?? ?? ?? ?? 48 85 D2 74 08 48 8B CB E8 ?? ?? ?? ?? 48 8B 15 ?? ?? ?? ?? 48 85 D2 74 0D"
        instruction_offset: 3
        is_relative: true

      - name: "LOCAL_PLAYER_DATA_ADDRESS"
        signature: "48 8B 15 ?? ?? ?? ?? 48 85 D2 74 08 48 8B CB E8 ?? ?? ?? ?? 48 8B 15 ?? ?? ?? ?? 48 85 D2 74 08 48 8B CB E8 ?? ?? ?? ?? 48 8B 15 ?? ?? ?? ?? 48 85 D2 74 0D"
        instruction_offset: 3
        is_relative: true

      - name: "DATA_TRAINING_DOJO_ROUNDS_LEFT"
        signature: "8B 05 ?? ?? ?? ?? 48 8B CE 4D 8B BE"
        instruction_offset: 2
        is_relative: true

      - name: "FUNC_WIREBUG_HIDE_AIM_ADDRESS"
        signature: "49 8B ?? ?? ?? ?? ?? ?? 48 83 60 50 FE 49 83 ?? ?? ?? ?? ?? ?? 00"
        instruction_offset: 8
        is_relative: false

      - name: "FUN_CALCULATE_ENTITY_DAMAGE"
        signature: "40 55 53 56 41 54 41 55 41 56 41 57 48 8D AC 24 ?? ?? ?? ?? 48 81 EC ?? ?? ?? ?? 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 85 ?? ?? ?? ?? 4C 8B AD"
        instruction_offset: 0
        is_relative: false

      - name: "SERVANTS_DATA_ADDRESS"
        signature: "48 8B 15 ?? ?? ?? ?? 48 85 D2 74 ?? 48 83 7A ?? 00 74 04 32 C0 EB 02 B0 01 0F B6 C0 48 89 74 24 ?? 48"
        instruction_offset: 3
        is_relative: true

      - name: "CRC_FUNC_1"
        signature: "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 56 48 83 EC 20 44 8B 05 ?? ?? ?? ?? 48 8B EA 8B 05 ?? ?? ?? ??"
        instruction_offset: 0
        is_relative: false

      - name: "CRC_FUNC_2"
        signature: "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 20 48 8B 5A 10 48 8B F2 48 8B 52 20 48 8B E9"
        instruction_offset: 0
        is_relative: false

      - name: "CRC_FUNC_3"
        signature: "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 20 4C 8B 05 ?? ?? ?? ?? 33 DB"
        instruction_offset: 0
        is_relative: false
        